### ISSUE TITLE
cabal: Could not resolve dependencies; ExitFailure 1

### ISSUE THREAD

**Issue by ickc** [mb21/pandoc-placetable#10]
Hi, I tried installing using `cabal install -f inlineMarkdown pandoc-placetable`, and the result is:

``` bash
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: pandoc-types-1.17.0.4/installed-MoT... (dependency of
pandoc-placetable-0.4)
trying: x509-system-1.6.4/installed-LCi... (dependency of
connection-0.2.6/installed-7Jp...)
rejecting: pandoc-placetable-0.4:-inlinemarkdown (constraint from config file,
command line flag, or user target requires opposite flag selection)
trying: pandoc-placetable-0.4:+inlinemarkdown
next goal: pandoc (dependency of pandoc-placetable-0.4:+inlinemarkdown)
rejecting: pandoc-1.17.2/installed-95F... (conflict: pandoc-types =>
aeson==1.0.2.0/installed-Iub..., pandoc => aeson==0.11.2.1/installed-B4z...)
rejecting: pandoc-1.17.2, pandoc-1.17.1, pandoc-1.17.0.3, pandoc-1.17.0.2,
pandoc-1.17.0.1, pandoc-1.17, pandoc-1.16.0.2, pandoc-1.16.0.1, pandoc-1.16
(conflict: pandoc-types==1.17.0.4/installed-MoT..., pandoc =>
pandoc-types>=1.16 && <1.17)
rejecting: pandoc-1.15.2.1, pandoc-1.15.2 (conflict: x509-system =>
process==1.4.2.0/installed-1.4..., pandoc => process>=1 && <1.4)
rejecting: pandoc-1.15.1.1, pandoc-1.15.1 (conflict: x509-system =>
process==1.4.2.0/installed-1.4..., pandoc => process>=1 && <1.3)
rejecting: pandoc-1.15.0.6, pandoc-1.15.0.5, pandoc-1.15.0.4, pandoc-1.15.0.3,
pandoc-1.15.0.2, pandoc-1.14.1 (conflict: pandoc-types =>
syb==0.6/installed-C65..., pandoc => syb>=0.1 && <0.6)
rejecting: pandoc-1.13.2.1, pandoc-1.13.2, pandoc-1.13.1, pandoc-1.13.0.1,
pandoc-1.13, pandoc-1.12.4.2, pandoc-1.12.4, pandoc-1.12.3.3, pandoc-1.12.3.2,
pandoc-1.12.3.1, pandoc-1.12.3, pandoc-1.12.2.1, pandoc-1.12.2, pandoc-1.12.1,
pandoc-1.12.0.2, pandoc-1.12.0.1, pandoc-1.12, pandoc-1.11.1, pandoc-1.11,
pandoc-1.10.1, pandoc-1.10.0.5, pandoc-1.10.0.4, pandoc-1.10.0.3,
pandoc-1.10.0.2, pandoc-1.10.0.1, pandoc-1.10, pandoc-1.9.4.5, pandoc-1.9.4.4,
pandoc-1.9.4.3, pandoc-1.9.4.2, pandoc-1.9.4.1, pandoc-1.9.4, pandoc-1.9.3,
pandoc-1.9.2, pandoc-1.9.1.2, pandoc-1.9.1.1, pandoc-1.9.1, pandoc-1.9.0.5,
pandoc-1.9.0.4, pandoc-1.9.0.3, pandoc-1.9.0.2, pandoc-1.9, pandoc-1.8.2.1,
pandoc-1.8.2, pandoc-1.8.1.2, pandoc-1.8.1.1, pandoc-1.8.1, pandoc-1.8.0.3,
pandoc-1.8.0.2, pandoc-1.8.0.1, pandoc-1.8, pandoc-1.6.0.1, pandoc-1.6,
pandoc-1.5.1.1, pandoc-1.5.1, pandoc-1.5.0.1, pandoc-1.5, pandoc-1.4,
pandoc-1.3, pandoc-1.2.1, pandoc-1.2, pandoc-1.1, pandoc-1.0.0.1, pandoc-1.0,
pandoc-0.46, pandoc-0.45, pandoc-0.44, pandoc-0.43, pandoc-0.42, pandoc-0.41,
pandoc-0.4 (conflict: pandoc-placetable-0.4:inlinemarkdown =>
pandoc>=1.14.0.0)
rejecting: pandoc-1.15.0.1, pandoc-1.15, pandoc-1.14.0.4, pandoc-1.14.0.3
(conflict: pandoc-types => syb==0.6/installed-C65..., pandoc => syb>=0.1 &&
<0.6)
rejecting: pandoc-1.14.0.2, pandoc-1.14.0.1 (conflict: pandoc-types =>
syb==0.6/installed-C65..., pandoc => syb>=0.1 && <0.5)
rejecting: pandoc-1.14 (conflict: pandoc-placetable-0.4:inlinemarkdown =>
pandoc>=1.14.0.0)
Backjump limit reached (currently 2000, change with --max-backjumps or try to
run with --reorder-goals).
```

Following suggestion in [When installing some filters, `cabal: Could not resolve dependencies...` - Google Groups](https://groups.google.com/forum/#!topic/pandoc-discuss/FajQP5pmLMg): `cabal install --allow-newer=base -f inlineMarkdown pandoc-placetable`, it then has the error:

``` bash
Resolving dependencies...
Downloading pandoc-placetable-0.4...
Configuring pandoc-placetable-0.4...
Building pandoc-placetable-0.4...
Failed to install pandoc-placetable-0.4
Build log ( ~/.cabal/logs/pandoc-placetable-0.4.log ):
cabal: Entering directory '/var/folders/2d/grhmr40j2bnc5bmd13pk582r0000gn/T/cabal-tmp-1416/pandoc-placetable-0.4'
Configuring pandoc-placetable-0.4...
Building pandoc-placetable-0.4...
Preprocessing executable 'pandoc-placetable' for pandoc-placetable-0.4...
[1 of 2] Compiling Paths_pandoc_placetable ( dist/build/autogen/Paths_pandoc_placetable.hs, dist/build/pandoc-placetable/pandoc-placetable-tmp/Paths_pandoc_placetable.o )
[2 of 2] Compiling Main             ( pandoc-placetable.hs, dist/build/pandoc-placetable/pandoc-placetable-tmp/Main.o )

pandoc-placetable.hs:142:15: error: parse error on input ‘then’
cabal: Leaving directory '/var/folders/2d/grhmr40j2bnc5bmd13pk582r0000gn/T/cabal-tmp-1416/pandoc-placetable-0.4'
cabal: Error: some packages failed to install:
pandoc-placetable-0.4 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by mb21** [comment]
right, I think this should be fixed with my last commit... will be pushing to hackage shortly, meanwhile you can try installing from github...

**Comment by ickc** [comment]
Thanks!

How about the dependency problem?

**Comment by mb21** [comment]
Not quite sure what's going on there... have you an older version of pandoc-types installed, or..? Try building in a cabal sandbox, or better yet, using `stack`...

**Comment by ickc** [comment]
Does `stack` allow the inlineMarkdown flag?

**Comment by mb21** [comment]
yes, try:

```
stack install --flag pandoc-placetable:inlineMarkdown
```

**Comment by ickc** [comment]
Thanks! I tried a few combination and the closest one is `stack build --flag pandoc-plactable:inlineMarkdown`. May be you can put the correct one in the readme too.

I actually don't know why there's such a dependency problem. I originally install pandoc through `brew install pandoc`. But later cabal did installed pandoc (probably to fulfill a dependency?). I was trying the `pandoc-csv2table` on the same day and the dependency problem that one has is `base <=4.9`. For yours, I just don't know why and all I know is the log complaining about the pandoc version.

I installed using your master branch through stack and everything works. Thank you!

**Comment by mb21** [comment]
Thanks, I updated the README and also pushed v0.4.1 to hackage, however it [seems](http://stackoverflow.com/questions/40259028/create-hackage-package-that-can-be-installed-with-stack) cloning from github and using `stack` is the way to go anyway...

**Comment by ickc** [comment]
Thanks. I saw that and installed via cabal already.

May I ask why stack is preferred over cabal? I tried searching stack vs. cabal and doesn't know which to choose. I finally chose cabal since I could use it as a package manager. (however I see post saying cabal is not a package manager, using cabal upgrade is deprecated and not recmmended.)

**Comment by mb21** [comment]
Here's the [official stack guide](https://docs.haskellstack.org/en/stable/GUIDE/). Among other things, `stack install` uses stackage as its repository which contains a curated set of versioned packages that are pretty much guaranteed to build with each other (unlike hackage that is used by `cabal install` where you can potentially run into dependency hell).

However, while `pandoc` is on stackage, I haven't gotten around to uploading `pandoc-placetable` to stackage (that's why you need to git clone it before you can install it). Personally, I think stack and stackage is _the future_, but not sure whether it's worth the effort for such a small package like `pandoc-placetable`... I haven't gotten a clear response [from the community](http://stackoverflow.com/questions/40259028/create-hackage-package-that-can-be-installed-with-stack).

**Comment by ickc** [comment]
Thanks for the info. I think the dependencies hell is exactly what I encountered in the beginning of this issue.
