### ISSUE TITLE
[Feature Request] Support for custom table styles

### ISSUE THREAD

**Issue by mickley** [mb21/pandoc-placetable#11]
Pandoc 1.18 introduces [custom styles for divs and spans ](http://pandoc.org/MANUAL.html#custom-styles-in-docx-output)in the docx writer.  

I think you're already [wrapping these tables in a div](https://github.com/mb21/pandoc-placetable/issues/6), so would it be possible to pass through the custom style as well?  Having the ability to style tables in Word would be very useful!

Currently, most tables are styled as "Compact", but those with inlinemarkdown turned on are styled as "Normal", which [causes some problems](https://github.com/mb21/pandoc-placetable/issues/7) as I pointed out before.

Wrapping the whole pandoc-placetable in a div already works, so I would think this would work.  It also opens up some flexibility for table formats.

**Comment by mb21** [comment]
Like:

``````
```{.table file="foo.csv" custom-style="my custom docx style"}
```
``````

Sounds good. The question is whether to pass through all the key-value-pairs from the codeblock to the generated div or only those with the key `custom-style`. Probably it's enough to only grab the `custom-key` attribute... classes and the id are already passed through and the others would just pollute the output, or are there more use cases I cannot think of?

**Comment by mickley** [comment]
Well, passing everything through is a bit more future-proofed.  Then it's up to the user to police what goes in the codeblock.

**Comment by mickley** [comment]
Also might be useful for those writing other filters that run after pandoc-placetable and could hook into custom options.

**Comment by mickley** [comment]
Awesome, thanks!

**Comment by mickley** [comment]
Hmm, it actually doesn't work with pandoc-crossref.  pandoc-crossref strips out that div you're wrapping it seems, so the custom-style attribute is lost.  

@lierdakil thoughts?  Stripping the div doesn't seem to me to be the best way to do things.  If you leave the div there, that would allow [linking cross references](https://github.com/lierdakil/pandoc-crossref/issues/30)

**Comment by lierdakil** [comment]
Could you create an issue on pandoc-crossref repo? Otherwise, I might forget about this -- so much to do, so little time.

For the moment, I'm thinking of leaving the divs in if there are attributes besides `id` set, or if cross-references links are requested. I don't really think it's a very good idea to wrap everything in a div unconditionally, since it changes document structure.
