### ISSUE TITLE
Requires http-conduit >= 2.2

### ISSUE THREAD

**Issue by mickley** [mb21/pandoc-placetable#12]
Earlier versions don't include parseUrlThrow

**Comment by mb21** [comment]
I replaced it since there was a warning that `parseUrl` is deprecated... is that a problem?

**Comment by mickley** [comment]
I had 2.1.8, which passed your test, but apparently doesn't include parseUrlThrow.  Took some work to figure it out, but 2.2.3 worked fine with no warnings.  I guess parseUrl was deprecated in 2.2.x

**Comment by mb21** [comment]
ah, now I get what you're saying: I forgot to update the .cabal file...
