### ISSUE TITLE
Bug Report: LaTeX error when CSV table has block element and no width specified

### ISSUE THREAD

**Issue by ickc** [mb21/pandoc-placetable#13]
I was using one of the example from [baig/pandoc-csv2table/grid.csv](https://github.com/baig/pandoc-csv2table/blob/master/Examples/csv/grid.csv):

#### Source

```markdown
~~~{.table inlinemarkdown=yes}
**_Fruit_**,~~Price~~,_Number_,`Advantages`
*Bananas~1~*,$1.34,12~units~,"Benefits of eating bananas 
(**Note the appropriately
rendered block markdown**):    

- _built-in wrapper_        
- ~~**bright color**~~

"
*Oranges~2~*,$2.10,5^10^~units~,"Benefits of eating oranges:

- **cures** scurvy
- `tasty`"
~~~
```

#### Command used

```bash
pandoc --filter pandoc-placetable -s -o placetable/grid.pdf source/grid.md
```

#### Error

```bash
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.76   \emph

pandoc: Error producing PDF
```

I noticed that the error probably is from the lack of the use of `minipage`.

#### Notes

However, if I use `pandoc --filter pandoc-placetable -o placetable/grid.md source/grid.md` to generate an intermediate markdown file first, that markdown file can be used to produce a PDF without error, e.g. `pandoc -s -o placetable/grid.pdf placetable/grid.md`.

By comparing the intermediate AST generated by the original markdown and the output markdown, I noticed that the problem probably comes from the lack of width. If the source is modified into this:

```markdown
~~~{.table inlinemarkdown=yes widths="0.25 0.25 0.25 0.25"}
**_Fruit_**,~~Price~~,_Number_,`Advantages`
*Bananas~1~*,$1.34,12~units~,"Benefits of eating bananas 
(**Note the appropriately
rendered block markdown**):    

- _built-in wrapper_        
- ~~**bright color**~~

"
*Oranges~2~*,$2.10,5^10^~units~,"Benefits of eating oranges:

- **cures** scurvy
- `tasty`"
~~~
```

Then the PDF can be generated without error.

**Comment by ickc** [comment]
By the way, I was comparing the output between pandoc-csv2table and pandoc-placetable, and I found that in the output of placetable, like this:

``` json
Pandoc (Meta {unMeta = fromList []})
[Table [] [AlignDefault,AlignDefault,AlignDefault,AlignDefault] [0.25,0.25,0.25,0.25]
 [[]
 ,[]
 ,[]
 ,[]]
 [[[Para [Strong [Emph [Str "Fruit"]]]]
  ,[Para [Strikeout [Str "Price"]]]
  ,[Para [Emph [Str "Number"]]]
  ,[Para [Code ("",[],[]) "Advantages"]]]
 ,[[Para [Emph [Str "Bananas",Subscript [Str "1"]]]]
  ,[Para [Str "$1.34"]]
  ,[Para [Str "12",Subscript [Str "units"]]]
  ,[Para [Str "Benefits",Space,Str "of",Space,Str "eating",Space,Str "bananas",SoftBreak,Str "(",Strong [Str "Note",Space,Str "the",Space,Str "appropriately",SoftBreak,Str "rendered",Space,Str "block",Space,Str "markdown"],Str "):"]
   ,BulletList
    [[Plain [Emph [Str "built-in",Space,Str "wrapper"],LineBreak]]
    ,[Plain [Strikeout [Strong [Str "bright",Space,Str "color"]]]]]]]
 ,[[Para [Emph [Str "Oranges",Subscript [Str "2"]]]]
  ,[Para [Str "$2.10"]]
  ,[Para [Str "5",Superscript [Str "10"],Subscript [Str "units"]]]
  ,[Para [Str "Benefits",Space,Str "of",Space,Str "eating",Space,Str "oranges:"]
   ,BulletList
    [[Plain [Strong [Str "cures"],Space,Str "scurvy"]]
    ,[Plain [Code ("",[],[]) "tasty"]]]]]]]
```

has a mysterious empty "list":

``` json
 [[]
 ,[]
 ,[]
 ,[]]
```

What was that?

**Comment by mb21** [comment]
I'll have to investigate... not sure whether all pandoc readers (and thus this filter as well) are supposed to generate widths (perhaps with all zeroes?) or if it's more of bug in the pandoc latex writer...

---

About the myserious empty list: it's a header row full of empty cells which was introduced in https://github.com/mb21/pandoc-placetable/commit/fd329d9c1c18f5da61903b081ab5d045ccc3c5ef because there was an error on some output formats I think. Note that the markdown reader does the same thing:

```
$ pandoc -t native

-------     ------ ----------   -------
     12     12        12             12
    123     123       123           123
      1     1          1              1
-------     ------ ----------   -------



[Table [] [AlignRight,AlignLeft,AlignCenter,AlignRight] [0.0,0.0,0.0,0.0]
 [[]
 ,[]
 ,[]
 ,[]]
 [[[Plain [Str "12"]]
  ,[Plain [Str "12"]]
  ,[Plain [Str "12"]]
  ,[Plain [Str "12"]]]
 ,[[Plain [Str "123"]]
  ,[Plain [Str "123"]]
  ,[Plain [Str "123"]]
  ,[Plain [Str "123"]]]
 ,[[Plain [Str "1"]]
  ,[Plain [Str "1"]]
  ,[Plain [Str "1"]]
  ,[Plain [Str "1"]]]]]
```

**Comment by ickc** [comment]
I see.

Regarding the empty widths, as far as I know (and documented in [Using all the features of tables in pandoc - Google Groups](https://groups.google.com/forum/#!searchin/pandoc-discuss/feature$20table%7Csort:relevance/pandoc-discuss/4HmB4V4L_uY/0cApDCjNAAAJ)), simple table has no sense of width, so the width will be a list of 0s. Pipe tables can optionally has widths, and the multiline and grid tables will definitely have widths.

I guess may be the internals of pandoc use the above properties to assume when there are multiline cells (block element), it will have non-zero widths. And this info will help to trigger the use of minipage in LaTeX output.

I wrote a filter similar to yours using panflute in [pandoc-table-csv-test/csv-tables.py at master · ickc/pandoc-table-csv-test](https://github.com/ickc/pandoc-table-csv-test/blob/master/bin/csv-tables.py#L115-L117), you can see the logic used to calculate the width automatically (a downside is if no metadata is set, the total width is assumed to be 1.0).

Sidenote: the reason I create the panflute filter is because of easier installation. I think it will be quite difficult to make sure the colleagues can handle the `cabal install...` thing, while the `pip` is ubiquitous and much easier to make sure they can install it. Hope that you don't mind! Among the existing pandoc CSV filters, mine takes most inspiration from yours. (I even experimenting with a way similar to pandoc-csv2table that writes an intermediate grid table.)

Continue from the point that it is difficult to install, that's the primary reason I made the suggestion above. The best case scenario would be it make into an official CSV reader (0 resistance to installation), the 2nd best case scenario is, if it has a cli, then it means the program can live independent of pandoc (hence no matching API version problem), and hence it is possible to distribute the binaries. Telling colleagues to install a binary would be much easier (both technically and psychologically: why are you asking me to install this unknown thing) than `cabal/stack`.

To further elaborate about a CSV reader in pandoc: if we can invent a standard way to include arbitrary format (say raw LaTeX in markdown, raw mediawiki in markdown, etc.), then we can introduce raw CSV in markdown, which would function similarly to what a CSV filter is currently doing. (I might actually be writing a panflute filter that works this way.)

**Comment by mb21** [comment]
Yes, so I'm just going to generate a list of zeroes if no widths are provided then.

> Sidenote: the reason I create the panflute filter is because of easier installation. 

Whatever works for you. But you can also copy the binary generated by `stack install` to other computers (or even the one by `stack build` and the corresponding cabal commands). Just make the binary executable (`chmod +x pandoc-placetable`) and place it somewhere on the `$PATH`.

**Comment by ickc** [comment]
Ah, this is not what I mean. I'm not sure if a list of 0s are ok. In mine I calculated the width automatically according to the length of the string (on each line). You might need to test it, I guess if it is a list of 0s, the LaTeX output would be infinitely narrowed table even if it compiles.

**Comment by ickc** [comment]
I just tested it, a list of 0s does not fix the bug (i.e. LaTeX output will still have error). The numbers has to be given in someway.

**Comment by mb21** [comment]
I guess the fundamental problem is that as soon as we have `Para` elements in the table cells (and not `Plain` ones anymore), i.e. as soon as you turn on `inlinemarkdown`, then some writers expect explicit widths with sensible numbers, since that's how the markdown `grid_tables` work (which are currently the only ones that can contain block elements).

**Comment by ickc** [comment]
Probably you are right. In my filter the width will be auto-calculated if not given (which seems to be desirable). You might restrict the case of auto-calculation only when it detects Para.

**Comment by mb21** [comment]
Yeah, but calculating the width of strings that are in markdown syntax is not very precise... but maybe better than just making the columns equal-width, which would also be a quick fix (and that's what the HTML reader seems to do as well).

**Comment by ickc** [comment]
But that simulate the calculation of column widths from a grid table very well. Say if you setup the grid tables "normally" where the padding is a character wide, and the text has markdown syntax. Then the column width up there really reflects the number of characters down there in markdown syntax.

I have thought about a more accurate calculation on the column width by converting the markdown in plain text first, but it seems too complicated (wasting computational time) while not reflecting how a markdown table would look like (for the reason above).

**Comment by ickc** [comment]
By the way, this is actually the forte of pandoc-csv2table, because it is giving pandoc a markdown representation and let pandoc do all the magic. But in the end yours is most poweful so I adopted your approach (that allow one to write tables that no markdown representation can represent. In the pandoc-discuss post I refered to above, no one pandoc table syntax provides all features supported by the internal AST Tables.)

**Comment by mb21** [comment]
> But that simulate the calculation of column widths from a grid table very well.

For one-liners yes, but what about lists etc? I'm just using `1 / nrColumns` for now, for simplicity's sake...

> By the way, this is actually the forte of pandoc-csv2table

It would seem that way. But ultimately it just feels too much of a hack to me (and I'm sure it's not too efficient). With pandoc-placetable's approach, you basically have to simulate the various pandoc readers... and sooner or later all the bugs in the different cases should be ironed out... (writing a test suite would help no doubt ;) )

Generating a huge markdown-table string is quite certainly more error-prone than generating the AST directly and the control over the AST this affords. Plus it comes without the benefit of the haskell type-checker.

btw, pull requests are always welcome :)

**Comment by ickc** [comment]
Ah, Somehoe this msg buried in my email inbox so I only read this now, sorry!

The auto calculation of widths are splited with `\n`, so the longest line (not whole cell) determines the cell width. So in a sense it is really like typing all those grid tables by hand. The only difference might be the padding which I don't check too careful about that. I see that jgm recently changed the way the column width is calculated to make sure round trip conversion is identical.

Sorry for not making a pull request, comprehending and writing Haskell is still a big challenge to me.
