### ISSUE TITLE
Feature Request: input from csv directly on cli

### ISSUE THREAD

**Issue by ickc** [mb21/pandoc-placetable#14]
It will be useful if the filter can be used as a standalone cli program.

e.g. currently, I could do this in a makefile:

```makefile
source/%.md: source/%.csv
	printf "%s\n" "~~~{.table inlinemarkdown=yes}" > $@
	cat $< >> $@
	printf "%s\n" "" "~~~" >> $@
```

to effectively wrap a csv around with the proper markdown code required by pandoc-placetable.

And my feature request would works somewhat like this:

```bash
pandoc-placetable -inlinemarkdown=yes source/table.csv | pandoc -f json -o ...
```

Since pandoc-placetable is already converting the CSV included into the pandoc AST, it seems natural to turn it into doing exactly only that. Effectively, it "adds" a CSV reader to pandoc.

I don't know if it make sense, perhaps it could even be added as an official CSV reader? What do @jgm think? I know previous discussions seem to rule out the possibility of having a markdown extension, say, `csv_tables` in official pandoc markdown. But being a CSV reader to turn into pandoc AST and output to any other format seems like a natural thing to do (except perhaps the "inlinemarkdown" part of the feature). e.g.

```bash
pandoc -f csv -t latex -o table.tex table.csv
```

**Comment by mb21** [comment]
Nice idea! It's probably best if you could just use the same key-value pairs on the commandline as you can now as attribute in the code block. I've started on reorganising the options parsing code for reuse, but might take a while till I'm done..
