### ISSUE TITLE
compile failure with pandoc-placetable-0.4.2

### ISSUE THREAD

**Issue by hvr** [mb21/pandoc-placetable#15]
Hi, your last Hackage upload results in a compile failure:

```
Configuring component exe:pandoc-placetable from pandoc-placetable-0.4.2
Preprocessing executable 'pandoc-placetable' for pandoc-placetable-0.4.2...
[1 of 2] Compiling Paths_pandoc_placetable ( /tmp/matrix-worker/1480766852/dist-newstyle/build/x86_64-linux/ghc-8.0.1/pandoc-placetable-0.4.2/c/pandoc-placetable/build/pandoc-placetable/autogen/Paths_pandoc_placetable.hs, /tmp/matrix-worker/1480766852/dist-newstyle/build/x86_64-linux/ghc-8.0.1/pandoc-placetable-0.4.2/c/pandoc-placetable/build/pandoc-placetable/pandoc-placetable-tmp/Paths_pandoc_placetable.o )
[2 of 2] Compiling Main             ( pandoc-placetable.hs, /tmp/matrix-worker/1480766852/dist-newstyle/build/x86_64-linux/ghc-8.0.1/pandoc-placetable-0.4.2/c/pandoc-placetable/build/pandoc-placetable/pandoc-placetable-tmp/Main.o )

pandoc-placetable.hs:135:13: error: parse error on input ‘let’
```

**Comment by mb21** [comment]
hm.. building with stack works fine for me... can you post the whole output? what OS and what GHC version are you on? with or without the INLINE_MARKDOWN flag?

**Comment by hvr** [comment]
It's actually the default build-plan cabal finds if you don't specify additional constraints for GHC 8.0. Here's the relevant fragments from `plan.json`:

```js
{
  "cabal-version": "1.25.0.0",
  "cabal-lib-version": "1.25.0.0",
  "compiler-id": "ghc-8.0.1",
  "os": "linux",
  "arch": "x86_64",
  "install-plan": [
   {
      "type": "configured",
      "id": "pandoc-placetable-0.4.2-inplace-pandoc-placetable",
      "pkg-name": "pandoc-placetable",
      "pkg-version": "0.4.2",
      "flags": {
        "inlinemarkdown": false
      },
      "style": "local",
      "dist-dir": "/tmp/pandoc-placetable-0.4.2/dist-newstyle/build/x86_64-linux/ghc-8.0.1/pandoc-placetable-0.4.2/c/pandoc-placetable",
      "depends": [
        "aeson-1.0.2.1-88a889649d6e1c1e26e3970129f603786338304e8a154efcfe975e794585cdde",
        "base-4.9.0.0",
        "bytestring-0.10.8.1",
        "explicit-exception-0.1.8-ec96006a1d526a32e8c29df3a31bdc386c5a9a69d8d9893807f5235bc6d6bc88",
        "http-conduit-2.2.3-bbab376ec5200232168098fb4188c499c458c743064c78ee9164cc92d2aa99d5",
        "pandoc-types-1.17.0.4-0bbf69617f6a2bd145b66f28ff5e539e3c9ea438c71d29f5a785d11044a9fb17",
        "spreadsheet-0.1.3.4-5bdd6a104056b6527d78c593a7eddb8b579fca2b6f56217a3d11fbd1e266e45e",
        "utf8-string-1.0.1.1-a53c33d3b03af574adf13ffb77be169ede6453a1e433d8add3bda15906ddb25b"
      ],
      "exe-depends": [],
      "component-name": "exe:pandoc-placetable",
      "bin-file": "/tmp/pandoc-placetable-0.4.2/dist-newstyle/build/x86_64-linux/ghc-8.0.1/pandoc-placetable-0.4.2/c/pandoc-placetable/build/pandoc-placetable/pandoc-placetable"
    },
// ...
```

Btw, did you really intend the `inlineMarkdown` cabal flag to be an automatic flag? It seems more like it's supposed to be a manual flag the solver shouldn't be allowed to toggle automatically.

**Comment by mb21** [comment]
I currently haven't `cabal-install` on my system. But using `stack install` (which uses GHC 8.0.1 as well with pandoc-placetable) works for me and certainly doesn't give a syntax error (which has nothing to do with the dependencies or the build system)... I'm on a Mac but that shouldn't make a difference...

---

> Btw, did you really intend the inlineMarkdown cabal flag to be an automatic flag? 

Not sure what you mean by that...

> the solver shouldn't be allowed to toggle [the flag] automatically.

Indeed, so what should I change?

**Comment by hvr** [comment]
@mb21 as for declaring the flag to be manual, see http://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-flag-manual

I suspect the CPP usage is to blame here... specifically the way the `#if` is indented, which may result in a faulty preprocessed .hs file, and it may explain why you get different results, as OSX's Clang `cpp` may result in a different output than GNU's `cpp`.

And in fact, if I edit the `#if`/`#else`/`#endif` CPP directives in the snippet below to start in the first column w/o any identation, it compiles fine.

```hs
    , Option "v" ["version"]
        (NoArg
          (\_ -> do
            #if defined(INLINE_MARKDOWN)
            let withInlineMarkdown = "with"
            #else
            let withInlineMarkdown = "without"
            #endif
            hPutStrLn stderr $ unlines [
```

I don't have time to investigate more right now; but my suggestion would be to have the `#` signs of CPP directives start in the first column of each line, to avoid any spurious whitespace being emitted by `cpp` processing

**Comment by mb21** [comment]
> CPP directives in the snippet below to start in the first column w/o any identation, it compiles fine.

Indeed, that must be it. This got indented when I refactored the code and I must have missed it...

I also added the `manual: true` to the flag... thanks for your help!

**Comment by hvr** [comment]
you're welcome... (fwiw, I hope that GHC 8.2 will come with its own native `cpp` processor so that we can get consistent behaviour on all platforms)
