### ISSUE TITLE
Error on csv file

### ISSUE THREAD

**Issue by lyndondrake** [mb21/pandoc-placetable#16]
Hi,

When I include this block:

` ```{.table file="/Users/lyndon/Documents/Study/Oxford/MSt/Dissertation/text/Neh5Heb.csv" header=yes aligns=LLRR caption="Nehemiah 5:1–13"}`
` ``` `

I get this output from pandoc:
`pandoc-placetable: Error in $: expected product (:*:), encountered Object `
`CallStack (from HasCallStack): `
`   error, called at ./Text/Pandoc/JSON.hs:125:13 in pandoc-types-1.16.1.15mFcOVb9FTfFbF4KbltdaC:Text.Pandoc.JSON `
` pandoc: Error running filter pandoc-placetable `
` Filter returned error status 1 `

Any thoughts?

Best,
Lyndon

**Comment by mb21** [comment]
I think that means your versions of pandoc and pandoc-types are not compatible. Try upgrading your pandoc version...

**Comment by lyndondrake** [comment]
Hmm, I'm on pandoc 1.19.2.1 which is the latest release. I've attached the file (with suffix altered for the upload) - does it work for you?
[Neh5Heb.txt](https://github.com/mb21/pandoc-placetable/files/1065832/Neh5Heb.txt)

**Comment by mb21** [comment]
Probably you need to build pandoc-placetable with pandoc-types `1.17.0.5` (personally, I use stack)

Because your error message says `pandoc-types-1.16.1.15`, yet:

    $ pandoc -v
    pandoc 1.19.2.1
    Compiled with pandoc-types 1.17.0.5

**Comment by lyndondrake** [comment]
No luck (even tried compiling it without and with the inlinemarkdown flag):
```
~/Documents/Study/Oxford/MSt/Dissertation$ pandoc -f markdown+pipe_tables+grid_tables+yaml_metadata_block -F pandoc-placetable --biblatex --template=build/template.latex -s -o formatted/Draft4.tex build/metadata.yaml text/1-Introduction.md text/2-Textual.md text/3-In-the-book.md text/4-In-the-versions.md text/5-Modern.md text/8-Conclusion.md text/9-Bibliography.md 
pandoc-placetable: Error in $: expected product (:*:), encountered Object
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:125:13 in pandoc-types-1.16.1.1-5mFcOVb9FTfFbF4KbltdaC:Text.Pandoc.JSON
Error running filter pandoc-placetable:
Filter returned error status 1
~/Documents/Study/Oxford/MSt/Dissertation$ which pandoc-placetable
/Users/lyndon/.local/bin/pandoc-placetable
~/Documents/Study/Oxford/MSt/Dissertation$ which pandoc
/Users/lyndon/.local/bin/pandoc
~/Documents/Study/Oxford/MSt/Dissertation$ pandoc --version
pandoc 2.0
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4, skylighting 0.3.3
Default user data directory: /Users/lyndon/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
~/Documents/Study/Oxford/MSt/Dissertation$ pandoc-placetable --version
pandoc-placetable 0.4.2
Compiled without the inlineMarkdown flag.
https://github.com/mb21/pandoc-placetable
~/Documents/Study/Oxford/MSt/Dissertation$ pandoc -f markdown+pipe_tables+grid_tables+yaml_metadata_block -F pandoc-placetable --biblatex --template=build/template.latex -s -o formatted/Draft4.tex build/metadata.yaml text/3-In-the-book.md 
pandoc-placetable: Error in $: expected product (:*:), encountered Object
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:125:13 in pandoc-types-1.16.1.1-5mFcOVb9FTfFbF4KbltdaC:Text.Pandoc.JSON
Error running filter pandoc-placetable:
Filter returned error status 1
~/Documents/Study/Oxford/MSt/Dissertation$ pandoc-placetable --version
pandoc-placetable 0.4.2
Compiled with the inlineMarkdown flag.
https://github.com/mb21/pandoc-placetable
~/Documents/Study/Oxford/MSt/Dissertation$
```

**Comment by lyndondrake** [comment]
actually I've just seen the reference there to pandoc-types-1.16.1.1…

Where is that coming from? I've now compiled both pandoc and pandoc-placetable with stack. But obviously one of them is still using the old types library. Have I done the ` git clone` wrong for pandoc-placetable somehow?

**Comment by mb21** [comment]
oh, I think I haven't updated the resolver in the stack.yaml for too long, can you try again? (i.e. `git pull`, then `stack build` again)

**Comment by lyndondrake** [comment]
Success! Thanks for your help in sorting it all out. Much appreciated.

**Comment by mb21** [comment]
thanks for the report!
