### ISSUE TITLE
Error running filter pandoc-placetable: Could not find executable pandoc-placetable

### ISSUE THREAD

**Issue by atanasj** [mb21/pandoc-placetable#18]
Hi,

I'm getting the error 'Error running filter pandoc-placetable: Could not find executable pandoc-placetable' when trying to run this filter on OS-X 10.12.6, with pandoc 2.0.2.

I have installed via cable as instructed (a couple of times), but to no avail. This is the message I get when installing the package:

Atanass-MacBook-Pro:~ atanas_____$ cabal install pandoc-placetable
Warning: --root-cmd is no longer supported, see
https://github.com/haskell/cabal/issues/3353 (if you didn't type --root-cmd,
comment out root-cmd in your ~/.cabal/config file)
Resolving dependencies...
Configuring pandoc-placetable-0.4.2...
Building pandoc-placetable-0.4.2...
Installed pandoc-placetable-0.4.2
Updating documentation index
/Users/atanas_____/Library/Haskell/share/doc/x86_64-osx-ghc-8.2.1/index.html 

I may be missing an obvious initial point in the install, I'm a bit new to installing packages from the terminal, so not sure what to do fairly regularly.

I've tried --filter and -Filter in the order: pandoc -F pandoc-placetable {other args, etc.} 

I'm hoping someone can please help?

**Comment by mb21** [comment]
not sure about the error you're getting... can you try with [stack](http://haskellstack.org) ?
https://github.com/mb21/pandoc-placetable#using-stack

**Comment by atanasj** [comment]
That worked, cheers. 

And thanks for putting together such as useful package, that works with pandoc-crossref to boot!
