### ISSUE TITLE
Working with pandoc2?

### ISSUE THREAD

**Issue by scokobro** [mb21/pandoc-placetable#19]
Seem to be unable to get pandoc-placetable to produce any output; keep getting the following error message:

`pandoc-placetable: Error in $: expected product (:*:), encountered Object`

Just wondering if it functions with pandoc 2?

**Comment by mb21** [comment]
What versions are you using? Works for me:

    ~ pandoc-placetable -v
    pandoc-placetable 0.4.2

    ~ pandoc -v
    pandoc 2.0.3

    ~ echo '# foo' | pandoc --filter pandoc-placetable
    <h1 id="foo">foo</h1>

**Comment by scokobro** [comment]
Hi - my results as follows...

```
- pandoc-placetable -v
pandoc-placetable 0.4.2

- pandoc -v
pandoc 2.0
Compiled with pandoc-types 1.17.2, texmath 0.9.4.4, skylighting 0.4.2

- echo '# foo' | pandoc --filter pandoc-placetable
pandoc-placetable: Error in $: expected product (:*:), encountered Object
Error running filter pandoc-placetable:
Filter returned error status 1

```

**Comment by mb21** [comment]
yes, try upgrading pandoc, you need it compiled with the same `pandoc-types` version

**Comment by scokobro** [comment]
Updated to pandoc 2.0.4 - still getting same error...

`pandoc-placetable: Error in $: expected product (:*:), encountered Object`

**Comment by mb21** [comment]
How are you installing them?

you can try fixing the `pandoc-types` version to the same your version of pandoc has. Modify [this line](https://github.com/mb21/pandoc-placetable/blob/master/pandoc-placetable.cabal#L39) and `stack install`

**Comment by scokobro** [comment]
Now functioning as expected. I was using quite an old version of ghc (7.10.2) updating this seems to have fixed it. Thanks for your help.
