### ISSUE TITLE
[Feature request] Allow selection and ordering of CSV lines and columns by additional attributes

### ISSUE THREAD

**Issue by pdfkungfoo** [mb21/pandoc-placetable#2]
1. Allow _selective processing_ of CSV lines (== table rows) into the generated tables. For example by supporting an additional attribute like `csvlines=3,7,33-end,2` (should be obvious what I mean with this). And the lines should appear in the same order as `cvslines=...` lists them.
2. Allow _selective_ processing of CSV columns (== table cols) into the table. For example by supporting an additional attribute like `csvcolumns=6,3,2,13,44-end` (similarly, allow re-arranging of order of columns).

Of course, these two features should also be working when combining them.

This feature would significantly ease the difficulty and amount of work that is required if you want to create smaller, selective tables from a larger CSV file, and it would spare the creation, handling and management of multiple, temporarily created smaller CSV files....

**Comment by mb21** [comment]
I'm not sure this should be included, would like to avoid feature-creep. There are already [plenty of tools](http://stackoverflow.com/questions/1063125/linux-tool-to-parse-csv-files) that do something like this, which you can run right before running pandoc, like:

```
cut -f 2,5,6 -d , file.csv > fileTemp.csv && pandoc --filter pandoc-placetable input.md
```

**Comment by pdfkungfoo** [comment]
To counter your argument of "feature creep" with a few of my own thoughts:
1. The external tools you hint at are available and usable by _you_ and by _me_, but not by the average Pandoc user, who very likely is not a shell scripting or general command line utility guru.
2. If taken at face value, you could apply that argument to this filter itself: after all, it is not _required_ in order to get tables to work in output formats -- users could easily write their own `pipe_tables` syntax by hand, so why should they get their hands on a filter that supports their lazyness and generates tables for them from CSV input?!?
3. While `cut` can easily select _columns_ (fields in CSV lines) -- what could be used to select a group of lines?
4. If this feature was available, it would be very easy to insert multiple "partial" tables created/derived/selected from one larger CSV, and all users who could at all handle the filter's options would be able to handle these extra options too. Without it they'd have to create and manage multiple temporary CSV files instead of a single (permanent) one. (_I have to do it now, and I'm using a similar method with external commands to select the parts I want -- and I don't like it!_)
5. My feature request was precisely motivated by the desire to _avoid_ the creation of extra temporary external CSV files -- and now you suggest to create extra temporary external CSV files as an alternative?!?

Just ask yourself:
- Would this additional feature...
  1. ...add significant value _for these users who would make use of my filter already_, 
  2. ...make the usage of the filter significantly more difficult for existing users,
  
  ...or would your _filter without the feature_ be less useful while easier to handle?

My opinion is clear:
1. This feature would add significant value (not just for me, but for many other potential users).
2. This feature would not add any user-unfriendliness to its usability.

Hence, nothing in sight that smells like *feature-creep"   :-)

**Comment by mb21** [comment]
Okay, let's look at the use-cases. So far I can see two:
1. cut off some rows and columns that were inserted in the spreadsheet software for layout purposes or stuff that you don't want to print (notes etc.)
2. enable the user to lump multiple tables in the same spreadsheet table, then cut them out again with the command you propose. (whenever the user inserts new rows in the upper table, he has to adjust the options in the markdown file or have rows silently disappear.)

Shouldn't we rather encourage the users to break out the cells they want to print in separate [sheets](http://i.stack.imgur.com/XFkrA.png), one for each pandoc table? (I think you can reference data from the main sheet, so your print sheets would update automagically.)

What rather annoys me more, is that I have to click "export to csv" all the time, so I was thinking of incorporating a [.xlsx](https://hackage.haskell.org/package/xlsx) file reader. I think Libre/Open Office can write those as well, which would leave google sheets, but for that I could apparently fetch the csv [from a URL of a _published_ spreadsheet](https://productforums.google.com/forum/#!topic/docs/IJyd_5A3u1A).

**Comment by mb21** [comment]
btw, just stumbled over [Miller — like sed, awk, cut, join, and sort for name-indexed data such as CSV](http://johnkerl.org/miller/).

**Comment by ickc** [comment]
@KurtPfeifle,

I just installed the filter and tested it. Using the example given:

``````
```{.table file="foo.csv" header=yes aligns=LRCRR inlinemarkdown=yes
     caption="my **caption**" delimiter="," quotechar="\"" }
\```
``````

The `aligns=LRCRR`, having 5 columns only, will truncate the numbers of columns (in my file it has 8 columns but only 5 are shown). You could use this behavior to hide the columns you don't want to show up. It isn't quite what you asked (and it doesn't hide rows), but better than nothing. And personally I agree the behavior you are asking should be done somewhere else.

@mb21,

> I was thinking of incorporating a .xlsx file reader

Is `.xlsx` support still under consideration?

**Comment by mb21** [comment]
Yeah, `xlsx` support would be nice, haven't really had time to look at it, but [xlsx](https://github.com/qrilka/xlsx) looks promising...
