### ISSUE TITLE
Weird dependencies

### ISSUE THREAD

**Issue by Ninoninoninonino** [mb21/pandoc-placetable#21]
This looks like a good idea -- but why is it installing so many dependencies, e.g. cryptonite? What elaborate processes are happening at the back end?

**Comment by mb21** [comment]
If you're compiling with the inlineMarkdown flag, it unfortunately needs to recompile a large part of pandoc...  see https://github.com/mb21/pandoc-placetable#the-inlinemarkdown-flag

Maybe we should provide binaries... but it's quite some work to set this up for all platforms..
