### ISSUE TITLE
[Feature request] Allow LaTeX to be formatted inside tables

### ISSUE THREAD

**Issue by wwwaldo** [mb21/pandoc-placetable#22]
Thanks for writing this pandoc filter!

I'd like to have tables with correctly formatted exponents, e.g. 10^9.

Normally pandoc lets me do this by adding dollar signs: $10^9$ if I'm converting from markdown to pdf.

However, if I import a CSV file with $10^9$ as an entry, the resulting table has plaintext $10^9$.

![screenshot from 2018-09-21 20-43-11](https://user-images.githubusercontent.com/17558590/45911270-fbd17e00-bdde-11e8-9806-799fd7e978f5.png)

Is there some way to add math formatting inside the table?

**Comment by mb21** [comment]
ha, weird that nobody has noticed this before! I quickly fixed this and made a new release. Now, for example this should work:

    echo 'foo, $10^9$' | pandoc-placetable --inlinemarkdown | pandoc -f json
