### ISSUE TITLE
Table format

### ISSUE THREAD

**Issue by c3018911** [mb21/pandoc-placetable#23]
Is it possible to set the table format when using pandoc-placetable?

For example, if I want a grid_table or pipe_table in the same document?

**Comment by mb21** [comment]
What's your output format? Markdown?

You can do that as you would normally with pandoc, see https://pandoc.org/MANUAL.html#extensions and https://pandoc.org/MANUAL.html#tables e.g.

    pandoc --filter pandoc-placetable -t markdown-grid_tables

**Comment by c3018911** [comment]
Thanks for a quick reply. Sorry, I should have given some more details. I am trying to output from markdown to pdf, but will also need to get it in to docx

**Comment by mb21** [comment]
Then I don't understand what you mean by table format. The input format that this filter uses is csv.

Can you give an example of what you're trying to do?

**Comment by c3018911** [comment]
I am trialling out using markdown/pandoc to write a manuscript. I have a csv with some data in it that is updated as the analysis changes. I then use pandoc-placetable to show the contents of the csv in the pdf. This works ok, I guess using the default format. But, I want to have a grid table format in the pdf to separate the columns etc. and make the table easier to read. 

For example I can use this to read in the data from the csv... 

    ```{.table #tbl:tbl_init_values header=yes caption="Initial values" file="tbl_init_values.csv" inlinemarkdown=yes}
    ```

**Comment by mb21** [comment]
> I want to have a grid table format in the pdf to separate the columns etc. 

The concept of grid_tables don't exist in the latex/pdf output. they exist only in the markdown input (and not at all when using pandoc-placetable). But maybe what you want is to set the column widths? If so, use the `width` option like `file="tbl_init_values.csv" widths="0.2 0.8"` etc. See https://github.com/mb21/pandoc-placetable/#usage

**Comment by mb21** [comment]
Closing this, since it's a question that should now be answered...
