### ISSUE TITLE
Incompatible API versions

### ISSUE THREAD

**Issue by c3018911** [mb21/pandoc-placetable#24]
Hi - sorry for another question... thanks in advance for any help. 

I've just switched across to MX Linux and am having troubles getting pandoc-placetable to work (installed through stack). The error I am getting is:

`pandoc-placetable: Error in $: Incompatible API versions: encoded with [1,20] but attempted to decode with [1,17,3,1].
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:122:13 in pandoc-types-1.17.3.1-2H9v0rGz1RlCFGpqGmPMq8:Text.Pandoc.JSON
Error running filter /home/gjb/.local/bin/pandoc-placetable:
Filter returned error status 1
done!`

My pandoc version is

`$ pandoc --version
pandoc 2.9.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: /home/gjb/.local/share/pandoc or /home/gjb/.pandoc`

I initially had some trouble installing with the following error:
`Warning: Installation path /home/gjb/.local/bin not found on the PATH environment variable.`

after running 

`$ stack install --flag pandoc-placetable:inlineMarkdown pandoc-placetable`.

This was resolved by using

`export PATH=~/.local/bin:$PATH`

`PATH=$PATH stack install --flag pandoc-placetable:inlineMarkdown pandoc-placetable`

**Comment by mb21** [comment]
Thanks for the report! Indeed, we'll have to compile this against the newest version of pandoc-types... I'll try to do this soon...

**Comment by c3018911** [comment]
Much appreciated - in the interim, which version of pandoc should I be using for this work?

**Comment by mb21** [comment]
I remember it working with pandoc 2.1...

since then, pandoc has switched `String` to `Text` in its internal AST, so would have to change this filter to work with that (pull request welcome!)

meanwhile, for simple cases pandoc now has a built-in csv reader:

    pandoc -f csv input.csv

**Comment by c3018911** [comment]
Just for reference, I installed pandoc 2.5 and the corresponding release of pandoc-placetable compatible with this version. :)

**Comment by mb21** [comment]
Okay, I just pushed a commit (and published to hackage): pandoc-placetable 0.6 should work with the current pandoc version...
