### ISSUE TITLE
How to install properly?

### ISSUE THREAD

**Issue by nsk7even** [mb21/pandoc-placetable#25]
I tried to install this via both methods (cabal and stack), but still there is no `pandoc-placetable` command available on my system.
What else is needed?

**Comment by mb21** [comment]
well...
- what was the output of the install commands? any errors?
- what OS are you on?
- did you try opening a new terminal? (I think PATH will be updated on terminal launch)

**Comment by nsk7even** [comment]
This is Ubuntu 18.04 here and I tried reopening the terminal.
These two commands stack and cabal were completely new to me and the output was really big. So maybe there were some errors, but it didn't ended with a message, telling me that something didn't worked.
But I found a different solution that I am using now. Thank you for your answer and sorry for your time :)
