### ISSUE TITLE
[Feature request] Allow headers to be defined in fenced block

### ISSUE THREAD

**Issue by pdfkungfoo** [mb21/pandoc-placetable#3]
> - **Allow the table header line to be defined inside the fenced code block. For example by supporting an additional option for the `header` attribute: `header="fenced"` (to mean: first line within the fenced part is to become the header) or `header="line 13"` (to mean: line 13 of the external CSV source file is to become the header).**

This is useful (also in combination with my other feature request) when you have rather large CSV files, but you do not want to change the headers (permanently or temporarily) just for the table inclusion in a Markdown/Pandoc document. (Some headers are fine for processing/maintaining the CSV table in a spreadsheet, but may not be good in their original version in a published document -- so you may define a current header line by noting it down in the fenced block).

**Comment by mb21** [comment]
You can already define headers in the fenced code block:

``````
```{.table file="foo.csv" header=yes}
Fruit,Quantity,Price
```
``````

For the discussion of the `line 13` feature, let's stick to #2.
