### ISSUE TITLE
[Feature Request] Table cell style matching pandoc

### ISSUE THREAD

**Issue by mickley** [mb21/pandoc-placetable#7]
Pandoc tables converted to .docx creates tables with table cells having the Compact style.  Those created with pandoc-placetable use the Normal style for table cells.  

This is problematic if the Normal style is double-spaced for example.

**Comment by mb21** [comment]
I'm not too familiar with docx, can you output the two examples (what pandoc-placetable generates and what you'd expect) to `-t native`?

**Comment by mb21** [comment]
There's no such thing as a _table cell style_ in the pandoc AST, I'll close this until you provide more details to what you're requesting.

**Comment by mickley** [comment]
Sorry for not answering sooner.

Your assertion above about AST lacking table cell styles is not quite correct.  Here is a simple test to illustrate:

## Table 1

```
   Fruit  Price        Advantages
--------  ------  --------------------
 Bananas  $1.34    Bright Color
 Oranges  $2.10    Oranges are orange

Table: Simple Table Caption
```

This produces the following JSON output

```
  [Table [Str "Simple",Space,Str "Table",Space,Str "Caption"] [AlignRight,AlignLeft,AlignCenter] [0.0,0.0,0.0]
 [[Plain [Str "Fruit"]]
 ,[Plain [Str "Price"]]
 ,[Plain [Str "Advantages"]]]
 [[[Plain [Str "Bananas"]]
  ,[Plain [Str "$1.34"]]
  ,[Plain [Str "Bright",Space,Str "Color"]]]
 ,[[Plain [Str "Oranges"]]
  ,[Plain [Str "$2.10"]]
  ,[Plain [Str "Oranges",Space,Str "are",Space,Str "orange"]]]]]
```

## Table 2

``````
```{.table header=yes aligns=RLC caption="Placetable caption"}
Fruit,Price,Advantages
Bananas,$1.34,"Bright color"
Oranges,$2.10,"Oranges are orange"
``````

This produces the following:

```
[Table [Str "Placetable caption"] [AlignRight,AlignLeft,AlignCenter] [0.0,0.0,0.0]
 [[Para [Str "Fruit"]]
 ,[Para [Str "Price"]]
 ,[Para [Str "Advantages"]]]
 [[[Para [Str "Bananas"]]
  ,[Para [Str "$1.34"]]
  ,[Para [Str "Bright color"]]]
 ,[[Para [Str "Oranges"]]
  ,[Para [Str "$2.10"]]
  ,[Para [Str "Oranges are orange"]]]]]
```

Note that in the pandoc-placetable example, table cells are saved as _Para_.  In the simple table example, they are saved as _Plain_. 

This slight differences propagates through at least the Docx writer.  The Plain strings are formatted with the "Compact" Word style.  The Para strings are formatted with the "Normal"  or default paragraph style.  

If the Normal style happens to be double-spaced, the table ends up double-spaced too and looking terrible.  This can be avoided if you change to using Plain, as the Compact style can stay single-spaced while the Normal is double-spaced.  

I think it's probably worth making your tables as close to pandoc's implementation as possible anyway, just to avoid unforseen and future problems.  On that note, it looks like your caption is handled slightly differently as well.  

Hope that explains things for you more thoroughly.

**Comment by mb21** [comment]
I see what you mean. Although in for example [grid tables](http://pandoc.org/README.html#extension-grid_tables), pandoc produces tables with _Para_ as well. But you're probably right that the _Plain_ ones are more common.

**Comment by mickley** [comment]
Hmm, you're right about grid tables in pandoc.  I'm unsure if this is a bug of a feature.  

Maybe cells need to be _Para_ to support block elements, which are unique to grid tables?

**Comment by mickley** [comment]
Did a quick test to see if block elements worked in the same way as in grid tables.  It seems that they're interpreted correctly with _Plain_ and with _Para_ (using 0.1.2).  So perhaps _Para_ for grid_tables is a bug in pandoc.  

However with both 0.1.2 and 0.2 any line breaks within a block element such as a code block are not honored in the final table when using pandoc-placetable.

**Comment by mb21** [comment]
For example the HTML writer produces from `Para`:

```
<table><tr><td align="right">
  <p>Bananas</p>
</td></tr></table>
```

and from `Plain`:

```
<table><tr><td align="right">
  Bananas
</td></tr></table>
```

> However with both 0.1.2 and 0.2 any line breaks within a block element such as a code block are not honored in the final table when using pandoc-placetable.

Really? With `{.table file="foo.csv" inlinemarkdown=yes }` the following works for me (when compiled with `cabal install -f inlineMarkdown`):

```
"foo","**bar**

    code
    block", bar
```

**Comment by mickley** [comment]
Yes, I tested something like this, and there were no linebreaks in the result:

``````
Fruit,*Price*,~~Advantages~~
Bananas,$1.34,**Bright Color**
Oranges,$2.10,"```
<!--- Markdown comment -->
## Testing header

*Oranges are orange*
```"
``````

**Comment by mb21** [comment]
Works for me, in HTML output:

```
<table>
<tbody>
<tr class="odd">
<td align="left"><p>Fruit</p></td>
<td align="left"><p><em>Price</em></p></td>
<td align="left"><p><del>Advantages</del></p></td>
</tr>
<tr class="even">
<td align="left"><p>Bananas</p></td>
<td align="left"><p>$1.34</p></td>
<td align="left"><p><strong>Bright Color</strong></p></td>
</tr>
<tr class="odd">
<td align="left"><p>Oranges</p></td>
<td align="left"><p>$2.10</p></td>
<td align="left"><pre><code>&lt;!--- Markdown comment --&gt;
## Testing header

*Oranges are orange*</code></pre></td>
</tr>
</tbody>
</table>
```

**Comment by mickley** [comment]
Ok, that's good.  Doesn't seem to work for tex/pdf or docx writers though.  Will try to figure out what's going on in JSON when I have some time.
